### ISSUE TITLE
What's causing: forbidden: User "system:anonymous" in some Cloud Providers

### ISSUE THREAD

**Issue by klustria** [kubernetes-incubator/apiserver-builder#225]
I deployed API-Server to Google's Managed GKE and Oracle's OCI via Terraform with Unmanaged k8s. The behavior on both these providers are exactly the same. Deploying through Helm would not succeed until adding a ClusterRole like this:

kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default

Once the API-Server is deployed and running, executing any kubectl command to the Custom Resource would fail:

> kubectl get eventprovider 
Error from server (Forbidden): eventproviders.auraevents.oracledx.com is forbidden: User "system:anonymous" cannot list eventproviders.auraevents.oracledx.com in the namespace "default"

Any ideas on what would be causing the user to be anonymous leading to this failure?

**Comment by pires** [comment]
Most probably you have RBAC enabled, which means that, by default, your cluster won't allow full, unprivileged access any more.

**Comment by klustria** [comment]
Any suggestions on what can be done?

**Comment by klustria** [comment]
After reading this:

https://kubernetes.io/docs/admin/authentication/#anonymous-requests

then I tried this:

kubectl create clusterrolebinding cluster-system-anonymous --clusterrole=cluster-admin --user=system:anonymous

and it solved the problem.

**Comment by ghuntley** [comment]
@klustria that command you have executed uplifts all anonymous requests to super-admin level access.  If this instance is publically running your probs hacked by now. :/

https://twitter.com/GeoffreyHuntley/status/1004636307828629504

**Comment by damongant** [comment]
Well, sort of @ghuntley 

This is concerning RBAC, not access to kubectl. The externally reachable apiserver endpoint has some [other authentication mechanism](https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#authentication) (usually TLS client certificates, but things like OIDC are possible too). RBAC is an additional layer of security that many clusters don't even use. The command above is just a novel way to set `--authorization-mode=NONE`

Anyway, back to the issue. We faced this problem too. When RBAC is enabled, the aggregated apiserver somehow has to figure out what user is sending a request. It then asks the kubernetes-apiserver if that user is allowed to perform said action. If the mechanism to tell the aggregated server the user is not working, it defaults to user:anonymous, which is then rejected.

You need to add some flags to kubernetes-apiserver for this to work, check [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/)

**Comment by klustria** [comment]
Appreciate the discussion still ongoing around this topic. I know that above approach I did is just a workaround and since we are not in production, I'm using it to get us going. @damongant, what exact flags from https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/ did you use exactly to make this work for you?

**Comment by damongant** [comment]
apiserver:
```
      --requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem
      --requestheader-allowed-names=aggregator
      --requestheader-extra-headers-prefix=X-Remote-Extra-
      --requestheader-group-headers=X-Remote-Group
      --requestheader-username-headers=X-Remote-User
```

**Comment by damongant** [comment]
Yes

**Comment by klustria** [comment]
Thanks I will try it out. The challenge of course is if you are working with Managed Kubernetes Clusters where you would have little to no ability to change the flags for the APIServer. If I recall, GKE has this issue too and I'm not sure if these flags can be set there. Currently, I'm using Unmanaged Cluster via terraform so I can try out those flags to see if it will work for me.

**Comment by markusdresch** [comment]
i managed to create a workaround by applying this yaml:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anonymous-logs-role
rules:
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anonymous-logs-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anonymous-logs-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:anonymous
```

this way logs, exec and attach work and the api server doesn't expose any information, so this isn't as permissive as AllowAll. any drawbacks?
